# Generated by Django 6.0.6 on 2026-06-28 02:45

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadtask',
            name='file_hash',
            field=models.CharField(default='', editable=False, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='uploadtask',
            name='source_file',
            field=models.FileField(editable=False, upload_to='study_uploads/'),
        ),
        # Seems like needs to custom sql to migrate to uuids
        migrations.RunSQL(
            sql=[
                'ALTER TABLE "studies_study" DROP CONSTRAINT "studies_study_pkey"',
                'ALTER TABLE "studies_study" DROP COLUMN "id"',
                'ALTER TABLE "studies_study" ADD COLUMN "id" uuid PRIMARY KEY DEFAULT gen_random_uuid()',
                'ALTER TABLE "studies_uploadtask" DROP CONSTRAINT "studies_uploadtask_pkey"',
                'ALTER TABLE "studies_uploadtask" DROP COLUMN "id"',
                'ALTER TABLE "studies_uploadtask" ADD COLUMN "id" uuid PRIMARY KEY DEFAULT gen_random_uuid()',
            ],
            reverse_sql=migrations.RunSQL.noop,
        )

    ]
