# Generated by Django 6.0.6 on 2026-06-29 03:50

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studies', '0002_uploadtask_file_hash_alter_study_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='study',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='uploadtask',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='uploadtask',
            name='source_file',
            field=models.FileField(upload_to='study_uploads/'),
        ),
    ]
