# Generated by Django 6.0.6 on 2026-06-29 04:41

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studies', '0003_alter_study_id_alter_uploadtask_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadtask',
            name='status',
            field=models.CharField(choices=[('new', 'New'), ('processing', 'Processing'), ('done', 'Done')], default='new', max_length=20),
        ),
        migrations.AlterField(
            model_name='uploadtask',
            name='file_hash',
            field=models.CharField(db_index=True, editable=False, max_length=64, unique=True),
        ),
        migrations.CreateModel(
            name='NctSearchTask',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('nct_id', models.CharField(db_index=True, max_length=11, unique=True)),
                ('status', models.CharField(choices=[('new', 'New'), ('processing', 'Processing'), ('done', 'Done')], default='new', max_length=20)),
                ('study', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='studies.study')),
                ('upload_task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='studies.uploadtask')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
