# Generated by Django 6.0.6 on 2026-06-29 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studies', '0004_uploadtask_status_alter_uploadtask_file_hash_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nctsearchtask',
            name='status',
            field=models.CharField(choices=[('new', 'New'), ('processing', 'Processing'), ('not found', 'Not Found'), ('failure', 'Failure'), ('done', 'Done')], default='new', max_length=20),
        ),
    ]
