# Generated by Django 6.0.6 on 2026-06-29 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studies', '0005_alter_nctsearchtask_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nctsearchtask',
            name='nct_id',
            field=models.CharField(db_index=True, max_length=11),
        ),
    ]
