# Generated by Django 6.0.6 on 2026-06-29 19:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('studies', '0006_alter_nctsearchtask_nct_id'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='nctsearchtask',
            unique_together={('nct_id', 'upload_task')},
        ),
    ]
